model:
    type: RCNN
    backbone:
        type: Resnet101
        return_stages: [layer3]
        pretrained: True
    rpn:
        type: RPN
        in_channels: 1024
        anchor_scales: [8, 16, 32]
        feat_strides: [16]
    roi_heads:
        type: BoxHead
        in_channels: 1024
        feat_strides: [16]

optim:
    type: "SGD"
    lr: 0.0025
    momentum: 0.9
    weight_decay: 0.0001

scheduler:
    type: StepLR
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.001
    milestones: [8, 11]

logger:
    type: "RunLogger"

work_dir: "./exp"
max_epoch: 12
checkpoint_interval: 1
eval_interval: 1
log_interval: 50

