model:
    type: RCNN
    backbone:
        type: Resnet50
        return_stages: [layer3]
        pretrained: True
    rpn:
        type: RPN
        in_channels: 1024
        scales: [8, 16, 32]
        feat_strides: [16]
    roi_heads:
        type: BoxHead
        in_channels: 1024
        feat_strides: [16]

dataset:
    train:
        type: COCODataset
        root: /home/lxl/workspace/JDet/coco128/images/train2017
        anno_file: /home/lxl/workspace/JDet/coco128/detections_train2017.json
        batch_size: 16
        num_workers: 4
        shuffle: True
        transforms:
            - type: "Resize"
              min_size: [800]
              max_size: 1333
            - type: "RandomFlip"
              prob: 0.5
            - type: Pad
              size_divisor: 32
            - type: "Normalize"
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]
    val:
        type: COCODataset
        root: /home/lxl/workspace/JDet/coco128/images/train2017
        anno_file: /home/lxl/workspace/JDet/coco128/detections_train2017.json
        batch_size: 2
        num_workers: 4
        shuffle: False
        transforms:
            - type: "Resize"
              min_size: [800]
              max_size: 1333
            - type: Pad
              size_divisor: 32
            - type: "Normalize"
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]
optim:
    type: "SGD"
    lr: 0.02
    momentum: 0.9
    weight_decay: 0.0001

scheduler:
    type: WarmUpLR
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.001

logger:
    type: "RunLogger"

work_dir: "./exp"
max_epoch: 300
eval_interval: 10
log_interval: 20
checkpoint_interval: 100

