model:
    type: RCNN
    backbone:
        type: Resnet50
        return_stages: [layer3]
        pretrained: True
    rpn:
        type: RPN
        in_channels: 1024
        anchor_scales: [8, 16, 32]
        feat_strides: [16]
    roi_heads:
        type: BoxHead
        in_channels: 1024
        feat_strides: [16]

dataset:
    train:
        type: YOLODataset
        path: /home/lxl/workspace/JDet/coco128/images/train2017
        batch_size: 8
        num_workers: 8
        shuffle: True
        transforms:
            - type: "Resize"
              min_size: [800]
              max_size: 1333
            - type: "RandomFlip"
              prob: 0.5
            - type: Pad
              size_divisor: 32
            - type: "Normalize"
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]

optim:
    type: "SGD"
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001

scheduler:
    type: StepLR
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.001
    milestones: [133,183]

logger:
    type: "RunLogger"

work_dir: "./exp"
max_epoch: 200
checkpoint_interval: 10
eval_interval: 1
log_interval: 20

