
model:
    type: RetinaNet
    backbone:
        type: Resnet50
        return_stages:  [layer1,layer2,layer3,layer4]
        pretrained: True
    neck:
        type: FPN
        in_channels: [256,512,1024,2048]
        out_channels: 256
        start_level: 1
        add_extra_convs: on_input
        num_outs: 5
    roi_head:
        type: RetinaHead
        n_class: 80
        in_channels: 256
        stacked_convs: 4
        feat_strides: [8, 16, 32, 64, 128]
        octave_base_scale: 4
        scales_per_octave: 3
        ratios: [0.5, 1.0, 2.0]

dataset:
    train:
        type: COCODataset
        root: /home/lxl/workspace/JDet/coco128/images/train2017
        anno_file: /home/lxl/workspace/JDet/coco128/detections_train2017.json
        batch_size: 2
        num_workers: 4
        shuffle: True
        transforms:
            - type: "Resize"
              min_size: [800]
              max_size: 1333
            - type: "RandomFlip"
              prob: 0.5
            - type: Pad
              size_divisor: 32
            - type: "Normalize"
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]
    val:
        type: COCODataset
        root: /home/lxl/workspace/JDet/coco128/images/train2017
        anno_file: /home/lxl/workspace/JDet/coco128/detections_train2017.json
        batch_size: 2
        num_workers: 4
        shuffle: False
        transforms:
            - type: "Resize"
              min_size: [800]
              max_size: 1333
            - type: Pad
              size_divisor: 32
            - type: "Normalize"
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]
optim:
    type: "SGD"
    lr: 0.00125
    momentum: 0.9
    weight_decay: 0.0001

scheduler:
    type: WarmUpLR
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.001

logger:
    type: "RunLogger"

work_dir: "./exp"
max_epoch: 300
eval_interval: 10
log_interval: 20
checkpoint_interval: 100

